[package]
name = "helium-crypto"
version = "0.3.2-dev"
authors = ["Marc Nijdam <marc@helium.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
thiserror = "1"
bs58 = {version = "0.4", features=["check"]}
signature = "*"
serde = "1"
rand_core = { version = "0.6", features = ["getrandom"] }
ed25519-dalek = { git = "https://github.com/helium/ed25519-dalek", branch = "madninja/bump_rand" }
p256 = { git = "https://github.com/helium/elliptic-curves", branch="madninja/compact_point_impl", default-features=false, features=["arithmetic", "ecdsa", "sha256", "zeroize", "ecdh"] }
ecc608-linux = { path = "../testing", version = "0", optional = true}

[features]
default = []
ecc608 = [ "ecc608-linux" ]

[dev-dependencies]
hex = "0"
hex-literal = "0"
rand = "0.8"
sha2 = "0"


